# Generated by Django 5.0.7 on 2024-07-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0003_alter_book_taken_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='loan_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
